-
  version: 2.2.1.{build}
  
  image: Visual Studio 2017
  
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
  configuration: Release
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
  before_build:
    - nuget restore
  build:
    publish_nuget: true
    verbosity: minimal
  deploy:
    provider: NuGet
    api_key:
      secure: u+bbUrM+dTHZcbRS57mKf79gPQP11USR96edhLf1JxUf84kjiYez1qzAtuvSvsQ5
    skip_symbols: false
    artifact: /.*\.nupkg/
-
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - master
  configuration: Release
  assembly_info:
    patch: false
  build:
    publish_nuget: true
    verbosity: minimal
  deploy:
    provider: NuGet
    api_key:
      secure: u+bbUrM+dTHZcbRS57mKf79gPQP11USR96edhLf1JxUf84kjiYez1qzAtuvSvsQ5
    skip_symbols: false
    artifact: /.*\.nupkg/
