version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: odKiOePzrS9/UvtZ91bU0Bo/yacIwsDZiNCZ88TOyepk8AY5JexNOKvnd1WzuODP
  skip_symbols: false
  artifact: /.*\.nupkg/
